### ISSUE TITLE
not an issue but a request

### ISSUE THREAD

**Issue by anointed** [rickharris/StickyScroll#4]
could you please provide an example of how to utilize this script with a fixed header/footer?

I've been trying to do this all evening with no luck, and would love to see a proper example of how to do this instead of my hacky code.

The concept is simple, have an fixed position header 40px on the top and a fixed position footer 100px on the bottom with your scroller in the middle..

thank you for your time and a great script

**Comment by anointed** [comment]
I should have mentioned that this is also a fluid layout. Primary use is for the ipad if that makes any difference.

**Comment by rickharris** [comment]
Actually, that kind of misses the point of what StickyScroll is for. The general use case is something like, "I have an element (typically a sidebar) that I want to _act_ like it's `position: fixed` only when the user scrolls down the page past a certain point, but also be contained so that it doesn't collide with elements outside of its container." It's not really a 1-to-1 replacement for using `position: fixed` in your CSS.

It sounds like you're looking for [iScroll](http://cubiq.org/iscroll-4).
